logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
server:
    error:
      whitelabel:
        enabled: false
    port: 8081
spring:
  sql:
    init:
      mode: never
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_DEF_PASS}
    url: jdbc:mysql://localhost:3306/food_delivery?createDatabaseIfNotExist=true
    username: ${DB_DEF_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
